2015-09-12 03:00:09,632 INFO:             errors [in app.py:30]
2015-09-12 03:00:19,234 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:00:19,438 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:04:40,381 ERROR:             Exception on /v1/ocr [POST] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:06:15,064 ERROR:             Exception on /v1/ocr [POST] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:21:06,450 ERROR:             Exception on /v1/ocr [POST] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:23:38,456 INFO:             errors [in app.py:30]
2015-09-12 03:23:46,348 ERROR:             Exception on /v1/ocr [POST] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:24:05,764 INFO:             errors [in app.py:30]
2015-09-12 03:24:12,423 ERROR:             Exception on /v1/ocr [POST] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:28:04,515 INFO:             errors [in app.py:30]
2015-09-12 03:29:03,442 INFO:             errors [in app.py:30]
2015-09-12 03:29:09,358 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:29:09,519 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:29:11,806 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:29:11,885 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:29:45,594 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:29:45,671 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:31:33,958 INFO:             errors [in app.py:30]
2015-09-12 03:31:38,998 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:31:39,123 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:31:41,123 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:31:41,251 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:38:56,322 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:38:57,674 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:38:57,788 ERROR:             Exception on /favicon.ico [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 03:42:04,932 INFO:             errors [in app.py:32]
2015-09-12 03:43:48,790 INFO:             errors [in app.py:20]
2015-09-12 03:45:05,120 INFO:             errors [in app.py:20]
2015-09-12 03:46:16,136 INFO:             errors [in app.py:51]
2015-09-12 14:33:42,989 INFO:             errors [in app.py:51]
2015-09-12 14:35:02,763 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
NameError: global name 'render_template' is not defined
2015-09-12 14:37:01,006 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
NameError: global name 'render_template' is not defined
2015-09-12 14:37:09,118 INFO:             errors [in app.py:51]
2015-09-12 14:37:12,064 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: layout.html
2015-09-12 14:38:09,853 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("../../templates/layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: layout.html
2015-09-12 14:38:17,176 INFO:             errors [in app.py:51]
2015-09-12 14:38:18,608 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("../../templates/layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ../../templates/layout.html
2015-09-12 14:40:40,826 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("../../templates/layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ../../templates/layout.html
2015-09-12 14:40:58,924 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ../../templates/layout.html
2015-09-12 14:41:06,002 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: ../../templates/layout.html
2015-09-12 14:41:20,583 INFO:             errors [in app.py:51]
2015-09-12 14:41:24,243 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/flask_server/templates/layout.html", line 8, in top-level template code
    <a href="{{ url_for('login') }}">log in</a>
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('login', {}, None)
2015-09-12 14:41:38,999 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    return render_template("layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/flask_server/templates/layout.html", line 8, in top-level template code
    <a href="{{ url_for('login') }}">log in</a>
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('login', {}, None)
2015-09-12 14:44:25,393 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 13, in hello
    def hello():
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/flask_server/templates/layout.html", line 8, in top-level template code
    <a href="{{ url_for('login') }}">log in</a>
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('login', {}, None)
2015-09-12 14:44:33,131 INFO:             errors [in app.py:61]
2015-09-12 14:44:34,911 ERROR:             Exception on / [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 14, in hello
    return render_template("layout.html")
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/flask_server/templates/layout.html", line 8, in top-level template code
    <a href="{{ url_for('login') }}">log in</a>
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('login', {}, None)
2015-09-12 15:14:54,886 INFO:             errors [in app.py:61]
2015-09-12 16:14:10,743 INFO:             errors [in app.py:61]
2015-09-12 16:16:04,423 INFO:             errors [in app.py:63]
2015-09-12 16:22:11,848 INFO:             errors [in app.py:63]
2015-09-12 16:25:38,121 INFO:             errors [in app.py:63]
2015-09-12 16:28:41,328 INFO:             errors [in app.py:63]
2015-09-12 16:30:15,931 INFO:             errors [in app.py:63]
2015-09-12 16:38:33,495 INFO:             errors [in app.py:63]
2015-09-12 16:38:59,964 INFO:             errors [in app.py:63]
2015-09-12 16:40:11,134 INFO:             errors [in app.py:63]
2015-09-12 16:43:18,375 INFO:             errors [in app.py:65]
2015-09-12 16:43:24,347 ERROR:             Exception on /v1/ocr [POST] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 16:45:07,294 INFO:             errors [in app.py:68]
2015-09-12 16:45:44,362 INFO:             errors [in app.py:68]
2015-09-12 16:49:45,119 INFO:             errors [in app.py:68]
2015-09-12 17:56:22,366 INFO:             errors [in app.py:68]
2015-09-12 20:40:51,236 INFO:             errors [in app.py:68]
2015-09-12 21:11:02,934 INFO:             errors [in app.py:72]
2015-09-12 21:11:04,638 ERROR:             Exception on /get-tex [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 21:12:17,337 ERROR:             Exception on /get-tex [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 21:12:26,999 INFO:             errors [in app.py:72]
2015-09-12 21:12:28,940 ERROR:             Exception on /get-tex [GET] [in /Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/Users/rosexu/PycharmProjects/latex-my-notes/web/webenv/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2015-09-12 21:18:10,254 INFO:             errors [in app.py:72]
2015-09-12 21:18:10,432 INFO:             errors [in app.py:72]
2015-09-12 21:20:40,328 INFO:             errors [in app.py:72]
2015-09-12 21:27:41,381 INFO:             errors [in app.py:74]
2015-09-12 21:34:23,267 INFO:             errors [in app.py:78]
2015-09-12 21:38:58,861 INFO:             errors [in app.py:80]
2015-09-12 21:38:59,096 INFO:             errors [in app.py:80]
2015-09-12 21:43:29,312 INFO:             errors [in app.py:80]
2015-09-12 21:43:29,516 INFO:             errors [in app.py:80]
2015-09-12 21:48:43,606 INFO:             errors [in app.py:81]
2015-09-12 21:49:35,003 INFO:             errors [in app.py:81]
2015-09-12 21:49:35,236 INFO:             errors [in app.py:81]
2015-09-12 21:49:51,822 INFO:             errors [in app.py:81]
2015-09-12 21:51:27,204 INFO:             errors [in app.py:81]
2015-09-12 21:53:13,599 INFO:             errors [in app.py:83]
2015-09-12 23:21:25,022 INFO:             errors [in app.py:94]
2015-09-12 23:21:25,282 INFO:             errors [in app.py:94]
2015-09-12 23:23:11,709 INFO:             errors [in app.py:94]
2015-09-12 23:29:02,154 INFO:             errors [in app.py:95]
2015-09-12 23:29:11,733 INFO:             errors [in app.py:95]
2015-09-12 23:29:46,604 INFO:             errors [in app.py:95]
2015-09-12 23:30:22,488 INFO:             errors [in app.py:95]
2015-09-12 23:34:18,014 INFO:             errors [in app.py:96]
2015-09-12 23:38:22,754 INFO:             errors [in app.py:96]
2015-09-12 23:40:18,390 INFO:             errors [in app.py:99]
2015-09-12 23:43:56,793 INFO:             errors [in app.py:99]
2015-09-12 23:44:13,419 INFO:             errors [in app.py:99]
2015-09-12 23:44:19,932 INFO:             errors [in app.py:99]
2015-09-12 23:47:16,006 INFO:             errors [in app.py:99]
2015-09-12 23:47:19,286 INFO:             errors [in app.py:100]
2015-09-12 23:49:52,390 INFO:             errors [in app.py:100]
2015-09-12 23:49:52,607 INFO:             errors [in app.py:100]
2015-09-12 23:52:21,364 INFO:             errors [in app.py:99]
2015-09-12 23:57:24,203 INFO:             errors [in app.py:99]
2015-09-12 23:57:24,427 INFO:             errors [in app.py:99]
2015-09-12 23:58:10,648 INFO:             errors [in app.py:99]
2015-09-12 23:58:10,846 INFO:             errors [in app.py:99]
2015-09-12 23:58:56,609 INFO:             errors [in app.py:99]
2015-09-12 23:58:56,841 INFO:             errors [in app.py:99]
2015-09-12 23:59:18,376 INFO:             errors [in app.py:99]
2015-09-12 23:59:18,546 INFO:             errors [in app.py:99]
2015-09-12 23:59:39,460 INFO:             errors [in app.py:99]
2015-09-12 23:59:39,629 INFO:             errors [in app.py:99]
=======
2015-09-12 20:19:50,275 INFO:             errors [in app.py:68]
2015-09-12 20:27:53,907 INFO:             errors [in app.py:68]
2015-09-12 20:44:46,510 INFO:             errors [in app.py:68]
2015-09-12 20:59:56,238 INFO:             errors [in app.py:73]
2015-09-12 21:07:49,930 INFO:             errors [in app.py:74]
2015-09-12 21:37:33,313 INFO:             errors [in app.py:75]
2015-09-12 21:50:52,558 INFO:             errors [in app.py:77]
2015-09-12 21:54:06,697 INFO:             errors [in app.py:77]
2015-09-12 21:54:09,392 ERROR:             Exception on /send-image [POST] [in /usr/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 23, in sendImage
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
NameError: global name 'filename' is not defined
2015-09-12 21:54:16,579 ERROR:             Exception on /send-image [POST] [in /usr/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)

  File "app.py", line 23, in sendImage
    file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
NameError: global name 'filename' is not defined
2015-09-12 21:55:36,495 INFO:             errors [in app.py:76]
2015-09-12 21:56:33,157 INFO:             errors [in app.py:78]
2015-09-12 21:58:05,079 INFO:             errors [in app.py:80]
2015-09-12 22:57:25,001 INFO:             errors [in app.py:79]
2015-09-13 00:13:47,289 INFO:             errors [in app.py:110]
2015-09-13 06:02:48,903 INFO:             errors [in app.py:110]
2015-09-13 06:02:49,102 INFO:             errors [in app.py:110]
2015-09-13 06:03:43,117 INFO:             errors [in app.py:110]
2015-09-13 06:12:38,979 INFO:             errors [in app.py:111]
2015-09-13 06:12:56,653 INFO:             errors [in app.py:111]
2015-09-13 06:13:06,180 INFO:             errors [in app.py:111]
2015-09-13 06:13:48,382 INFO:             errors [in app.py:111]
2015-09-13 06:13:52,970 INFO:             errors [in app.py:111]
2015-09-13 06:13:53,164 INFO:             errors [in app.py:111]
2015-09-13 06:22:22,338 INFO:             errors [in app.py:111]
2015-09-13 06:22:22,544 INFO:             errors [in app.py:111]
2015-09-13 06:24:19,387 INFO:             errors [in app.py:112]
2015-09-13 06:28:49,599 INFO:             errors [in app.py:118]
2015-09-13 06:28:49,824 INFO:             errors [in app.py:118]
2015-09-13 06:33:12,110 INFO:             errors [in app.py:118]
2015-09-13 06:33:41,142 INFO:             errors [in app.py:119]
2015-09-13 06:33:42,456 INFO:             errors [in app.py:119]
2015-09-13 06:34:39,567 INFO:             errors [in app.py:119]
2015-09-13 06:35:41,708 INFO:             errors [in app.py:121]
2015-09-13 06:37:06,094 INFO:             errors [in app.py:123]
2015-09-13 06:37:44,112 INFO:             errors [in app.py:125]
2015-09-13 06:38:10,910 INFO:             errors [in app.py:125]
2015-09-13 06:40:15,764 INFO:             errors [in app.py:124]
2015-09-13 06:42:05,308 INFO:             errors [in app.py:124]
2015-09-13 06:42:05,504 INFO:             errors [in app.py:124]
2015-09-13 06:43:46,296 INFO:             errors [in app.py:124]
2015-09-13 06:44:20,135 INFO:             errors [in app.py:124]
2015-09-13 06:44:24,574 INFO:             errors [in app.py:124]
2015-09-13 06:44:24,824 INFO:             errors [in app.py:124]
2015-09-13 06:45:25,041 INFO:             errors [in app.py:125]
2015-09-13 06:45:45,396 INFO:             errors [in app.py:125]
2015-09-13 06:45:45,667 INFO:             errors [in app.py:125]
2015-09-13 06:47:35,525 INFO:             errors [in app.py:125]
2015-09-13 06:47:40,900 INFO:             errors [in app.py:125]
2015-09-13 06:47:41,102 INFO:             errors [in app.py:125]
2015-09-13 06:48:24,068 INFO:             errors [in app.py:124]
2015-09-13 06:49:02,776 INFO:             errors [in app.py:124]
2015-09-13 06:49:02,977 INFO:             errors [in app.py:124]
2015-09-13 06:59:10,282 INFO:             errors [in app.py:124]
2015-09-13 06:59:51,350 INFO:             errors [in app.py:124]
2015-09-13 07:00:16,382 INFO:             errors [in app.py:123]
2015-09-13 07:00:27,013 INFO:             errors [in app.py:124]
2015-09-13 07:11:53,067 INFO:             errors [in app.py:125]
2015-09-13 07:11:58,628 INFO:             errors [in app.py:125]
2015-09-13 07:12:12,283 INFO:             errors [in app.py:125]
2015-09-13 07:17:53,217 INFO:             errors [in app.py:127]
2015-09-13 07:36:00,263 INFO:             errors [in app.py:128]
2015-09-13 07:36:12,986 INFO:             errors [in app.py:128]
2015-09-13 07:37:20,242 INFO:             errors [in app.py:130]
2015-09-13 07:38:45,711 INFO:             errors [in app.py:129]
2015-09-13 07:44:15,383 INFO:             errors [in app.py:126]
2015-09-13 07:47:44,933 INFO:             errors [in app.py:127]
2015-09-13 07:47:45,179 INFO:             errors [in app.py:127]
2015-09-13 07:51:37,148 INFO:             errors [in app.py:128]
2015-09-13 07:52:06,095 INFO:             errors [in app.py:128]
2015-09-13 07:54:04,874 INFO:             errors [in app.py:128]
2015-09-13 07:56:05,709 INFO:             errors [in app.py:130]
2015-09-13 07:56:41,653 INFO:             errors [in app.py:130]
2015-09-13 07:59:23,041 INFO:             errors [in app.py:133]
2015-09-13 08:00:17,277 INFO:             errors [in app.py:131]
2015-09-13 08:00:26,947 INFO:             errors [in app.py:130]
2015-09-13 08:00:37,629 INFO:             errors [in app.py:130]
2015-09-13 08:00:51,339 INFO:             errors [in app.py:130]
2015-09-13 08:01:24,328 INFO:             errors [in app.py:131]
2015-09-13 08:05:13,229 INFO:             errors [in app.py:132]
2015-09-13 08:05:26,856 INFO:             errors [in app.py:132]
2015-09-13 08:06:20,213 INFO:             errors [in app.py:133]
2015-09-13 08:06:53,312 INFO:             errors [in app.py:133]
2015-09-13 08:07:43,432 INFO:             errors [in app.py:133]
2015-09-13 08:08:23,470 INFO:             errors [in app.py:132]
2015-09-13 08:08:27,919 INFO:             errors [in app.py:132]
2015-09-13 08:08:31,365 INFO:             errors [in app.py:132]
2015-09-13 08:09:31,724 INFO:             errors [in app.py:132]
2015-09-13 08:17:51,204 INFO:             errors [in app.py:132]
2015-09-13 08:25:22,042 INFO:             errors [in app.py:133]
2015-09-13 08:25:22,277 INFO:             errors [in app.py:133]
2015-09-13 08:30:11,589 INFO:             errors [in app.py:137]
2015-09-13 08:30:11,827 INFO:             errors [in app.py:137]
2015-09-13 08:30:55,976 INFO:             errors [in app.py:138]
2015-09-13 08:31:34,942 INFO:             errors [in app.py:138]
2015-09-13 08:40:02,956 INFO:             errors [in app.py:139]
2015-09-13 08:41:31,763 INFO:             errors [in app.py:140]
2015-09-13 08:42:08,867 INFO:             errors [in app.py:140]
